<?php

namespace Tests\Unit\Bugfix;

use App\Models\MUserDetail;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Illuminate\Support\Facades\DB;

class Redmine12767Test extends TestCase
{

    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setTestData();
    }


    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_delMonth()
    {

        $model = new MUserDetail();

        // 更新テストデータ
        $detail = [
            'userId' => 'test01',
            'password' => '0000',
            'name' => 'name',
            'departmentJob' => 'departmentJob',
            'mail' => 'mail',
            'idMailBcc' => '',
            'delFlg' => 0,
        ];

        $updData = [
            'userCompany' => ['companyId' => 'companyId'],
            'plan' => [
                'contractPlanId' => 'plan',
                'userDetail' => [$detail]
            ]
        ];
        $dt = new \DateTime();

        // 有効 => 有効
        $model->updateUserDetail($updData, 'plan');
        $data = $model->get('companyId', 'plan', 'test01');

        $this->assertEquals(0, $data['delFlg']);
        $this->assertEquals(null, $data['delMonth']);

        // 有効 => 無効

        $updData['plan']['userDetail'][0]['delFlg'] = 1;

        $model->updateUserDetail($updData, 'plan');
        $data = $model->get('companyId', 'plan', 'test01');

        $this->assertEquals(1, $data['delFlg']);
        $this->assertEquals($dt->format('Ym'), $data['delMonth']);

        // 無効 => 有効

        $updData['plan']['userDetail'][0]['delFlg'] = 0;

        $model->updateUserDetail($updData, 'plan');
        $data = $model->get('companyId', 'plan', 'test01');

        $this->assertEquals(0, $data['delFlg']);
        $this->assertEquals(null, $data['delMonth']);


    }

    /**
     * テストデータの登録
     * @return void
     */
    private function setTestData()
    {

        DB::table('mContractPlan')->insert([
            'contractPlanId' => 'plan',
            'name' => 'plan',
            'planType' => 'plan',
            'idPrice' => 100,
            'unitPrice' => 100
        ]);


        DB::table('mUserDetail')->insert([
            'companyId' => 'companyId',
            'contractPlanId' => 'plan',
            'userId' => 'test01',
            'password' => '0000',
            'name' => 'name',
            'mail' => 'mail',
            'delflg' => 0,
            'delMonth' => null
        ]);

    }

}
