<?php

namespace Tests\Unit\Bugfix;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;
use Illuminate\Support\Facades\DB;
use App\Models\TClaim;
use Database\Seeders\AdminUserSeeder;
use Database\Seeders\CompanySeeder;
use Database\Seeders\ContractPlanSeeder;
use Database\Seeders\ContractStatusSeeder;
use Database\Seeders\ContractTypeSeeder;
use Database\Seeders\ConvertFontSeeder;
use Database\Seeders\CorporationSeeder;
use Database\Seeders\PersonSeeder;
use Database\Seeders\PrefectureSeeder;
use Database\Seeders\VatSeeder;
use DateTime;

class Redmine15860Test extends TestCase
{
    private array $requestData;
    private array $expectResponseWeb;
    private array $expectResponseApi;
    private array $expectResponseWebTrial;
    private array $expectResponseApiTrial;
    private array $exceptResponseAcuris;

    // 設定値
    //契約形態組み合わせ
    private int $patternFirst = 3;
    private int $patternMiddle = 3;
    private int $patternLast = 3;

    //ユーザ数
    private int $userQty = 2;

    //1日あたりの検索数
    private int $historyQty = 2;

    //ID代
    private int $IDPrice = 30000;

    //検索を何日分作成するか　関数内で設定
    private int $historyDate;

    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setTestData();
    }


    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_get_price_response_trial()
    {
        $TClaim = new TClaim();

        //予想レスポンスデータと、プログラムの取得結果を比較()
        for ($i = 1; $i <= $this->patternFirst * $this->patternMiddle * $this->patternLast; $i++) {
            $companyIds = []; //初期化
            $companyIds[] = sprintf('ent%02d', $i);
            $response = $TClaim->getList("2023-12", null, $companyIds, null, false, false);

            // 不一致ならデータ出力
            if ($this->expectResponseWebTrial[$i - 1] !== $response[0]->items['web']) {
                dump('$i: ' . $i);
                dump($this->expectResponseWebTrial[$i - 1]);
                dump($response[0]->items['web']);
            }

            // 不一致ならデータ出力
            if ($this->expectResponseApiTrial[$i - 1] !== $response[0]->items['api']) {
                dump('$i: ' . $i);
                dump($this->expectResponseApiTrial[$i - 1]);
                dump($response[0]->items['api']);
            }

            //getPriceで取得しているwebとapiの値をチェック
            $this->assertEquals($this->expectResponseWebTrial[$i - 1], $response[0]->items['web']);
            $this->assertEquals($this->expectResponseApiTrial[$i - 1], $response[0]->items['api']);

        }
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function test_get_price_response()
    {
        $TClaim = new TClaim();

        //予想レスポンスデータと、プログラムの取得結果を比較()
        for ($i = 1; $i <= $this->patternFirst * $this->patternMiddle * $this->patternLast; $i++) {
            $companyIds = []; //初期化
            $companyIds[] = sprintf('ent%02d', $i);
            $response = $TClaim->getList("2024-01", null, $companyIds, null, false, false);

            // 不一致ならデータ出力
            if ($this->expectResponseWeb[$i - 1] !== $response[0]->items['web']) {
                dump('$i: ' . $i);
                dump($this->expectResponseWeb[$i - 1]);
                dump($response[0]->items['web']);
            }

            // 不一致ならデータ出力
            if ($this->expectResponseApi[$i - 1] !== $response[0]->items['api']) {
                dump('$i: ' . $i);
                dump($this->expectResponseApi[$i - 1]);
                dump($response[0]->items['api']);
            }

            //getPriceで取得しているwebとapiの値をチェック
            $this->assertEquals($this->expectResponseWeb[$i - 1], $response[0]->items['web']);
            $this->assertEquals($this->expectResponseApi[$i - 1], $response[0]->items['api']);

            //acurisのチェック
            $this->assertEquals($this->exceptResponseAcuris[$i - 1], $response[0]->acurisItems);
        }
    }

    /**
     * テストデータの登録
     * @return void
     */
    private function setTestData()
    {
        //プラン
        $plan = [
            'normal',
            'small',
            'large'
        ];

        //契約種別
        $planType = [
            [
                'name' => '全額デポ',
                'typeId' => 'allDepo',
                'title' => '法人名・個人名検索(残高不足)'
            ],
            [
                'name' => 'IDデポ',
                'typeId' => 'idDepo',
                'title' => '法人名・個人名検索'
            ],
            [
                'name' => '毎月請求',
                'typeId' => 'allMonth',
                'title' => '法人名・個人名検索'
            ]
        ];

        $this->seed(AdminUserSeeder::class, 'hds-jcis-test');
        $this->seed(CompanySeeder::class, 'hds-jcis-test');
        $this->seed(ContractPlanSeeder::class, 'hds-jcis-test');
        $this->seed(ContractStatusSeeder::class, 'hds-jcis-test');
        $this->seed(ContractTypeSeeder::class, 'hds-jcis-test');
        $this->seed(ConvertFontSeeder::class, 'hds-jcis-test');
        $this->seed(CorporationSeeder::class, 'hds-jcis-test');
        $this->seed(PersonSeeder::class, 'hds-jcis-test');
        $this->seed(PrefectureSeeder::class, 'hds-jcis-test');
        $this->seed(VatSeeder::class, 'hds-jcis-test');

        //契約形態2回変更、3×3×3のパターンを作成
        for ($first = 0; $first < $this->patternFirst; $first++) {
            for ($middle = 0; $middle < $this->patternMiddle; $middle++) {
                for ($last = 0; $last < $this->patternLast; $last++) {
                    $planAry[] = [
                        'name' => $planType[$first]['name'] . '→' . $planType[$middle]['name'] . '→' . $planType[$last]['name'],
                        'first' => [
                            'planId' => $plan[rand(0, 2)],
                            'typeId' => $planType[$first]['typeId'],
                            'title' => $planType[$first]['title'],
                        ],
                        'middle' => [
                            'planId' => $plan[rand(0, 2)],
                            'typeId' => $planType[$middle]['typeId'],
                            'title' => $planType[$middle]['title'],
                        ],
                        'last' => [
                            'planId' => $plan[rand(0, 2)],
                            'typeId' => $planType[$last]['typeId'],
                            'title' => $planType[$last]['title'],
                        ],
                    ];
                }
            }
        }

        //契約形態を月中に2回変更、(3×3×3)
        for ($i = 1; $i <= $this->patternFirst * $this->patternMiddle * $this->patternLast; $i++) {
            // ユーザーマスタ
            DB::table('mUserCompany')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'name' => sprintf('株式会社アントレンド%02d %s', $i, $planAry[$i - 1]['name']),
                'kana' => sprintf('アントレンド%02d', $i),
                'postCode' => '1080023',
                'address' => '東京都港区芝浦2-14-13 MCK芝浦ビル6F',
                'tel' => '03-5444-2500',
                'staffName' => sprintf('担当者%02d', $i),
                'staffDepartmentJob' => sprintf('担当部%02d', $i),
                'staffTel' => '03-5444-2501',
                'staffMail' => 'naoki_hagiwara@entrend.net',
                'claimName' => '経理部担当者',
                'claimDepartmentJob' => '経理部',
                'claimTel' => '03-5444-2502',
                'claimMailTo' => 'keiri@entrend.net,naoki_hagiwara@entrend.net',
                'claimMailCc' => 'keiri_cc@entrend.net,naoki_hagiwara@entrend.net',
                'claimMailBcc' => 'keiri_bcc@entrend.net,naoki_hagiwara@entrend.net',
                'deliveryDate' => '3営業日以内',
                'paymentTerm' => 1,
                'freeFlg' => 0,
                'freePeriod' => 0,
                'chargeName' => sprintf('窓口担当者%02d', $i),
                'chargeMail' => sprintf('mado%02d@entrend.net', $i),
                'contractStatus' => 2,
                'delFlg' => 0,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);

            // 契約プラン
            // WEB
            DB::table('tContractPlan')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => $planAry[$i - 1]['last']['planId'],
                'contractTypeId' => 0,
                'startTrial' => '2023-01-01',
                'useStartDate' => '2024-01-01',
                'useUpdateDate' => '2024-01-21',
                'useEndAlertDate' => '2024-12-21',
                'useEndDate' => '2025-1-21',
                'idUnitPrice' => 0,
                'searchUnitPrice' => 0,
                'searchCount' => 0,
                'deposit' => 300000,
                'trialSearchUnitPrice' => 290,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);

            // API
            DB::table('tContractPlan')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => 'api',
                'contractTypeId' => 0,
                'startTrial' => '2023-01-01',
                'useStartDate' => '2024-01-01',
                'useUpdateDate' => '2024-01-21',
                'useEndAlertDate' => '2024-12-21',
                'useEndDate' => '2025-1-21',
                'idUnitPrice' => 0,
                'searchUnitPrice' => 0,
                'searchCount' => 0,
                'deposit' => 300000,
                'trialSearchUnitPrice' => 290,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);

            // 契約プラン履歴(2回変更)
            // WEB
            DB::table('tContractPlanDetail')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => $planAry[$i - 1]['first']['planId'],
                'seqNo' => 1,
                'contractTypeId' => $planAry[$i - 1]['first']['typeId'],
                'contractStartDate' => '2024-01-01',
                'contractEndDate' => '2024-01-10',
                'idUnitPrice' => 10000,
                'searchUnitPrice' => 100,
                'searchCount' => 100,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);
            DB::table('tContractPlanDetail')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => $planAry[$i - 1]['middle']['planId'],
                'seqNo' => 2,
                'contractTypeId' => $planAry[$i - 1]['middle']['typeId'],
                'contractStartDate' => '2024-01-11',
                'contractEndDate' => '2024-01-20',
                'idUnitPrice' => 20000,
                'searchUnitPrice' => 200,
                'searchCount' => 200,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);
            DB::table('tContractPlanDetail')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => $planAry[$i - 1]['last']['planId'],
                'seqNo' => 3,
                'contractTypeId' => $planAry[$i - 1]['last']['typeId'],
                'contractStartDate' => '2024-01-21',
                'contractEndDate' => '2025-01-21',
                'idUnitPrice' => $this->IDPrice,
                'searchUnitPrice' => 300,
                'searchCount' => 300,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);

            // API
            DB::table('tContractPlanDetail')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => 'api',
                'seqNo' => 1,
                'contractTypeId' => $planAry[$i - 1]['first']['typeId'],
                'contractStartDate' => '2024-01-01',
                'contractEndDate' => '2024-01-10',
                'idUnitPrice' => 10000,
                'searchUnitPrice' => 100,
                'searchCount' => 100,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);
            DB::table('tContractPlanDetail')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => 'api',
                'seqNo' => 2,
                'contractTypeId' => $planAry[$i - 1]['middle']['typeId'],
                'contractStartDate' => '2024-01-11',
                'contractEndDate' => '2024-01-20',
                'idUnitPrice' => 20000,
                'searchUnitPrice' => 200,
                'searchCount' => 200,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);
            DB::table('tContractPlanDetail')->insert([
                'companyId' => sprintf('ent%02d', $i),
                'contractPlanId' => 'api',
                'seqNo' => 3,
                'contractTypeId' => $planAry[$i - 1]['last']['typeId'],
                'contractStartDate' => '2024-01-21',
                'contractEndDate' => '2025-01-21',
                'idUnitPrice' => $this->IDPrice,
                'searchUnitPrice' => 300,
                'searchCount' => 300,
                'createDatetime' => date('Y/m/d h:i:s'),
                'updateDatetime' => date('Y/m/d h:i:s')
            ]);

            // ユーザー詳細
            // WEB
            for ($userWeb = 1; $userWeb <= $this->userQty; $userWeb++) {
                DB::table('mUserDetail')->insert([
                    'companyId' => sprintf('ent%02d', $i),
                    'contractPlanId' => $planAry[$i - 1]['last']['planId'],
                    'userId' => sprintf('jcis-ent%02d-%03d', $i, $userWeb),
                    'password' => 0000,
                    'name' => sprintf('WEB担当者%02d', $i),
                    'departmentJob' => '開発部',
                    'mail' => sprintf('jcis-ent%02d-%03d@entrend.net', $i, $userWeb),
                    'idMailBcc' => 'id_bcc@entrend.net',
                    'loginDatetime' => null,
                    'lockFlg' => 0,
                    'delFlg' => 0,
                    'delMonth' => null,
                    'createDatetime' => date('Y/m/d h:i:s'),
                    'updateDatetime' => date('Y/m/d h:i:s')
                ]);
            }

            // API
            for ($userApi = 1; $userApi <= $this->userQty; $userApi++) {
                DB::table('mUserDetail')->insert([
                    'companyId' => sprintf('ent%02d', $i),
                    'contractPlanId' => 'api',
                    'userId' => sprintf('jcisapi-ent%02d-%03d', $i, $userApi),
                    'password' => 0000,
                    'name' => sprintf('API担当者%02d', $i),
                    'departmentJob' => '開発部',
                    'mail' => sprintf('jcisapi-ent%02d-%03d@entrend.net', $i, $userApi),
                    'idMailBcc' => 'id_bcc@entrend.net',
                    'loginDatetime' => null,
                    'lockFlg' => 0,
                    'delFlg' => 0,
                    'delMonth' => null,
                    'createDatetime' => date('Y/m/d h:i:s'),
                    'updateDatetime' => date('Y/m/d h:i:s')
                ]);
            }

            ////////////////
            //検索履歴の作成 
            ////////////////   
            for ($userId = 1; $userId <= $this->userQty; $userId++) {

                // 検索日時
                $startDate = new \DateTime('2023-12-01');
                $endDate = new \DateTime('2024-01-31');
                $interval = new \DateInterval('P5D');
                $this->historyDate = 2;

                $period = new \DatePeriod($startDate, $interval, $endDate);

                //最初のプランに設定
                $webContractPlanId = $planAry[$i - 1]['first']['planId'];
                $depoFlg = $planAry[$i - 1]['first']['typeId'] === 'allDepo' ? true : false;
                $trialFlg = true;

                //1日おきでループ
                foreach ($period as $date) {
                    // 2024/01/21以降 最終プランに変更
                    if ($date >= new \DateTime('2024-01-21')) {
                        $webContractPlanId = $planAry[$i - 1]['last']['planId'];
                        $depoFlg = $planAry[$i - 1]['last']['typeId'] === 'allDepo' ? true : false;
                    } else if ($date >= new \DateTime('2024-01-11')) {
                        // 2024/01/11以降 中間プランに移行
                        $webContractPlanId = $planAry[$i - 1]['middle']['planId'];
                        $depoFlg = $planAry[$i - 1]['middle']['typeId'] === 'allDepo' ? true : false;
                    }

                    // 2023/12/31以降トライアル終了
                    if ($date >= new \DateTime('2023-12-31')) {
                        $trialFlg = false;
                    }

                    $depositFlg = 0;
                    // 全額デポ かつ トライアルでは無い時
                    if ($depoFlg === true && $trialFlg === false) {
                        $depositFlg = 1;
                    }

                    // 検索履歴追加 WEBとAPI
                    for ($history = 1; $history <= $this->historyQty; $history++) {
                        DB::table('tKeywordHistory')->insert([
                            'companyId' => sprintf('ent%02d', $i),
                            'contractPlanId' => $webContractPlanId,
                            'userId' => sprintf('jcis-ent%02d-%03d', $i, $userId),
                            'hash' => uniqid(),
                            'expireDate' => $date->format('YmdHisv'),
                            'keyword' => uniqid(),
                            'searchDate' =>  $date->format('Y-m-d'),
                            'chargeFlg' => $depositFlg,
                        ]);

                        DB::table('tKeywordHistory')->insert([
                            'companyId' => sprintf('ent%02d', $i),
                            'contractPlanId' => 'api',
                            'userId' => sprintf('jcisapi-ent%02d-%03d', $i, $userId),
                            'hash' => uniqid(),
                            'expireDate' => $date->format('YmdHisv'),
                            'keyword' => uniqid(),
                            'searchDate' =>  $date->format('Y-m-d'),
                            'chargeFlg' => $depositFlg,
                        ]);
                    }
                    //海外検索追加
                    DB::table('tAcurisKeywordHistory')->insert([
                        'companyId' => sprintf('ent%02d', $i),
                        'userId' => sprintf('jcisapi-ent%02d-%03d', $i, $userId),
                        'searchDate' =>  $date->format('Y-m-d'),
                        'searchCount' => 10,
                        'lookupCount' => 5,
                        'errSearchCount' => 0,
                        'errLookupCount' => 0,
                    ]);
                }
            }

            $idMonthly = [];
            $idYearly = [];
            $idTotalPrice = 0;
            $deposit = [];
            $totalPrice = 0;
            $contractType = '';
            $trial = [];
            $payPerUse = [];
            $overageCharges = 0;

            //予想レスポンスデータの作成(lastの契約形態ごとに作成)
            if ($planAry[$i - 1]['last']['typeId'] === 'allDepo') {
                //全額デポの時
                $idMonthly = [
                    "amount" => 0,
                    "unitPrice" => 0,
                    "price" => 0
                ];
                $idYearly = [
                    "amount" => $this->userQty,
                    "unitPrice" => $this->IDPrice * 12, //12カ月分
                    "price" => $this->IDPrice * 12 * $this->userQty,
                    "startDate" => "2024-01-21",
                    "endDate" => "2025-01-21"
                ];
                $idTotalPrice = $this->IDPrice * 12 * $this->userQty;
                $deposit = [
                    "amount" => 300,
                    "unitPrice" => 300,
                    "price" => 90000,
                    "startDate" => "2024-01-21",
                    "endDate" => "2025-01-21"
                ];
                $totalPrice = ($this->IDPrice * 12 * $this->userQty) + 90000 + (100 * $this->userQty * $this->historyQty *  $this->historyDate) + (200 * $this->userQty * $this->historyQty *  $this->historyDate) + (300 * $this->userQty * $this->historyQty *  $this->historyDate);
                $contractType = 'allDepo';
                $trial = [
                    "amount" => 0,
                    "unitPrice" => 290,
                    "price" => 0,
                    "startDate" => "2023/01/01",
                    "endDate" => "2023/12/31"
                ];
                $payPerUse = [
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 100,
                        "price" => 100 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-01",
                        "endDate" => "2024-01-10",
                        "title" => $planAry[$i - 1]['first']['title'],
                    ],
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 200,
                        "price" => 200 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-11",
                        "endDate" => "2024-01-20",
                        "title" => $planAry[$i - 1]['middle']['title'],
                    ],
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 300,
                        "price" => 300 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-21",
                        "endDate" => "2024-01-31",
                        "title" => $planAry[$i - 1]['last']['title'],
                    ],
                    "total" => (100 * $this->userQty * $this->historyQty *  $this->historyDate) + (200 * $this->userQty * $this->historyQty *  $this->historyDate) + (300 * $this->userQty * $this->historyQty *  $this->historyDate),
                ];
                $overageCharges = 0;
                if ($planAry[$i - 1]['first']['typeId'] === 'allDepo') {
                    $overageCharges += (100 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
                if ($planAry[$i - 1]['middle']['typeId'] === 'allDepo') {
                    $overageCharges += (200 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
                if ($planAry[$i - 1]['last']['typeId'] === 'allDepo') {
                    $overageCharges += (300 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
            } else if ($planAry[$i - 1]['last']['typeId'] === 'idDepo') {
                //IDデポの時
                $idMonthly = [
                    "amount" => 0,
                    "unitPrice" => 0,
                    "price" => 0
                ];
                $idYearly = [
                    "amount" => $this->userQty,
                    "unitPrice" => $this->IDPrice * 12, //12カ月分
                    "price" => $this->IDPrice * 12 * $this->userQty,
                    "startDate" => "2024-01-21",
                    "endDate" => "2025-01-21"
                ];
                $idTotalPrice = $this->IDPrice * 12 * $this->userQty;
                $deposit = [
                    "amount" => 300,
                    "unitPrice" => 300,
                    "price" => 0,
                    "startDate" => "2024-01-21",
                    "endDate" => "2025-01-21"
                ];
                $totalPrice = ($this->IDPrice * 12 * $this->userQty) + (100 * $this->userQty * $this->historyQty *  $this->historyDate) + (200 * $this->userQty * $this->historyQty *  $this->historyDate) + (300 * $this->userQty * $this->historyQty *  $this->historyDate);
                $contractType = 'idDepo';
                $trial = [
                    "amount" => 0,
                    "unitPrice" => 290,
                    "price" => 0,
                    "startDate" => "2023/01/01",
                    "endDate" => "2023/12/31"
                ];
                $payPerUse = [
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 100,
                        "price" => 100 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-01",
                        "endDate" => "2024-01-10",
                        "title" => $planAry[$i - 1]['first']['title'],
                    ],
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 200,
                        "price" => 200 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-11",
                        "endDate" => "2024-01-20",
                        "title" => $planAry[$i - 1]['middle']['title'],
                    ],
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 300,
                        "price" => 300 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-21",
                        "endDate" => "2024-01-31",
                        "title" => $planAry[$i - 1]['last']['title'],
                    ],
                    "total" => (100 * $this->userQty * $this->historyQty *  $this->historyDate) + (200 * $this->userQty * $this->historyQty *  $this->historyDate) + (300 * $this->userQty * $this->historyQty *  $this->historyDate),
                ];
                $overageCharges = 0;
                if ($planAry[$i - 1]['first']['typeId'] === 'allDepo') {
                    $overageCharges += (100 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
                if ($planAry[$i - 1]['middle']['typeId'] === 'allDepo') {
                    $overageCharges += (200 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
                if ($planAry[$i - 1]['last']['typeId'] === 'allDepo') {
                    $overageCharges += (300 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
            } else {
                //毎月請求の時
                $idMonthly = [
                    "amount" => $this->userQty,
                    "unitPrice" => $this->IDPrice,
                    "price" => $this->IDPrice * $this->userQty,
                ];
                $trialIdMonthly = [
                    "amount" => 0,
                    "unitPrice" => 0,
                    "price" => 0,
                ];

                $idYearly = [
                    "amount" => 0,
                    "unitPrice" => 0,
                    "price" => 0,
                ];

                $idTotalPrice = $this->IDPrice * $this->userQty;
                $trialIdTotalPrice = 0;

                $deposit = [
                    "amount" => 300,
                    "unitPrice" => 300,
                    "price" => 0,
                    "startDate" => "2024-01-21",
                    "endDate" => "2025-01-21"
                ];
                $trialDeposit = [
                    "amount" => 0,
                    "unitPrice" => 0,
                    "price" => 0,
                    "startDate" => "2024-01-21",
                    "endDate" => "2025-01-21"
                ];

                $totalPrice = ($this->IDPrice * $this->userQty) + (100 * $this->userQty * $this->historyQty *  $this->historyDate) + (200 * $this->userQty * $this->historyQty *  $this->historyDate) + (300 * $this->userQty * $this->historyQty *  $this->historyDate);
                $contractType = 'allMonth';
                $trialContractType = null;
                $trial = [
                    "amount" => 0,
                    "unitPrice" => 290,
                    "price" => 0,
                    "startDate" => "2023/01/01",
                    "endDate" => "2023/12/31"
                ];
                $payPerUse = [
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 100,
                        "price" => 100 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-01",
                        "endDate" => "2024-01-10",
                        "title" => $planAry[$i - 1]['first']['title'],
                    ],
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 200,
                        "price" => 200 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-11",
                        "endDate" => "2024-01-20",
                        "title" => $planAry[$i - 1]['middle']['title'],
                    ],
                    [
                        "amount" => $this->userQty * $this->historyQty *  $this->historyDate,
                        "unitPrice" => 300,
                        "price" => 300 * $this->userQty * $this->historyQty *  $this->historyDate,
                        "startDate" => "2024-01-21",
                        "endDate" => "2024-01-31",
                        "title" => $planAry[$i - 1]['last']['title'],
                    ],
                    "total" => (100 * $this->userQty * $this->historyQty *  $this->historyDate) + (200 * $this->userQty * $this->historyQty *  $this->historyDate) + (300 * $this->userQty * $this->historyQty *  $this->historyDate),
                ];
                $overageCharges = 0;
                if ($planAry[$i - 1]['first']['typeId'] === 'allDepo') {
                    $overageCharges += (100 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
                if ($planAry[$i - 1]['middle']['typeId'] === 'allDepo') {
                    $overageCharges += (200 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
                if ($planAry[$i - 1]['last']['typeId'] === 'allDepo') {
                    $overageCharges += (300 * $this->userQty * $this->historyQty *  $this->historyDate);
                }
            }

            $trialTrial = [
                "amount" => 28,
                "unitPrice" => 290,
                "price" => 8120,
                "startDate" => "2023/01/01",
                "endDate" => "2023/12/31"
            ];

            $trialPayPerUse = [
                [
                    "amount" => 0,
                    "unitPrice" => 0,
                    "price" => 0,
                ],
                "total" => 0
            ];

            $trialOverageCharges = 0;

            //トライアルの合計金額、トライアル合計を足して、従量課金の合計を引く
            $trialTotalPrice = $totalPrice + 8120 - 4800;

            $this->expectResponseWeb[] = [
                "idMonthly" => $idMonthly,
                "idYearly" =>  $idYearly,
                "idTotalPrice" => $idTotalPrice,
                "deposit" =>  $deposit,
                "totalPrice" => $totalPrice,
                "contractType" => $contractType,
                "trial" => $trial,
                "payPerUse" =>  $payPerUse,
                "overageCharges" => $overageCharges
            ];

            $this->expectResponseApi[] = [
                "idMonthly" => $idMonthly,
                "idYearly" =>  $idYearly,
                "idTotalPrice" => $idTotalPrice,
                "deposit" =>  $deposit,
                "totalPrice" => $totalPrice,
                "contractType" => $contractType,
                "trial" => $trial,
                "payPerUse" =>  $payPerUse,
                "overageCharges" => $overageCharges
            ];

            //毎月請求のときのトライアル取得結果
            if ($planAry[$i - 1]['last']['typeId'] === 'allMonth') {
                $this->expectResponseWebTrial[] = [
                    "idMonthly" => $trialIdMonthly,
                    "idYearly" =>  $idYearly,
                    "idTotalPrice" => $trialIdTotalPrice,
                    "deposit" =>  $trialDeposit,
                    "totalPrice" => 8120,
                    "contractType" => $trialContractType,
                    "trial" => $trialTrial,
                    "payPerUse" =>  $trialPayPerUse,
                    "overageCharges" => $trialOverageCharges
                ];

                $this->expectResponseApiTrial[] = [
                    "idMonthly" => $trialIdMonthly,
                    "idYearly" =>  $idYearly,
                    "idTotalPrice" => $trialIdTotalPrice,
                    "deposit" =>  $trialDeposit,
                    "totalPrice" => 8120,
                    "contractType" => $trialContractType,
                    "trial" => $trialTrial,
                    "payPerUse" =>  $trialPayPerUse,
                    "overageCharges" => $trialOverageCharges
                ];
            } else {
                $this->expectResponseWebTrial[] = [
                    "idMonthly" => $idMonthly,
                    "idYearly" =>  $idYearly,
                    "idTotalPrice" => $idTotalPrice,
                    "deposit" =>  $deposit,
                    "totalPrice" => $trialTotalPrice,
                    "contractType" => $contractType,
                    "trial" => $trialTrial,
                    "payPerUse" =>  $trialPayPerUse,
                    "overageCharges" => $trialOverageCharges
                ];

                $this->expectResponseApiTrial[] = [
                    "idMonthly" => $idMonthly,
                    "idYearly" =>  $idYearly,
                    "idTotalPrice" => $idTotalPrice,
                    "deposit" =>  $deposit,
                    "totalPrice" => $trialTotalPrice,
                    "contractType" => $contractType,
                    "trial" => $trialTrial,
                    "payPerUse" =>  $trialPayPerUse,
                    "overageCharges" => $trialOverageCharges
                ];
            }

            $this->exceptResponseAcuris[] = [
            "payPerUse" => [
                [
                "amount" => "120",
                "unitPrice" => 500,
                "price" => 60000,
                "detailFlg" => 0,
                ],
                [
                "amount" => "60",
                "unitPrice" => 1500,
                "price" => 90000,
                "detailFlg" => 1,
                ],
                "total" => 150000,
            ],
            "totalPrice" => 150000
            ];
        }
    }
}
